# Production environment override
services:
  sound-extractor:
      build:
          dockerfile: ./Dockerfile
          target: prod
          args:
              SERVICE_PORT: 5000
              SERVICE_NAME: sound-extractor
